name: ab_test_service
description: "A new Flutter package project."
version: 0.0.4
homepage: https://github.com/RuslanTsitser/ab_test_service

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  apphud: ^2.7.0
  shared_preferences: ^2.5.3
  http: ^1.4.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
